[pytest]
pythonpath = .

markers =
    regression: regression test suite

addopts =
    -s
    --headed
    --screenshot only-on-failure
    --video retain-on-failure
    --tracing retain-on-failure
    --alluredir allure-results
    --clean-alluredir